<a href="https://colab.research.google.com/github/soumensen411/Machine-Learning-Model/blob/main/%20hyperparameter%20tuning%20techniques/GridSearchCV%26RandomizedSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [191]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [192]:
df = sns.load_dataset("iris")

In [193]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [194]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [195]:
from sklearn.model_selection import train_test_split

In [196]:
X = df.drop('species',axis=1)
y = df['species']

In [197]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [198]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN = KNeighborsClassifier(n_neighbors=9)

In [199]:
model_KNN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [200]:
y_pred = model_KNN.predict(X_test)

In [201]:
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

In [202]:
from sklearn.metrics import accuracy_score

In [203]:
accuracy_score(y_pred,y_test)

1.0

In [204]:
from sklearn.svm import SVC

In [205]:
model_svm = SVC(gamma='auto')

In [206]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [207]:
model_svm.score(X_test,y_test)

1.0

# GRID SEARCH CV

In [208]:
from sklearn.model_selection import GridSearchCV

In [209]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
     'kernel':['rbf','linear']
},cv = 5, return_train_score=False)

In [210]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [211]:
print(classifier.cv_results_)

{'mean_fit_time': array([0.00482373, 0.0026269 , 0.00270209, 0.00296025, 0.0027482 ,
       0.00253725, 0.00294218, 0.00286269]), 'std_fit_time': array([3.89193624e-03, 2.87600845e-04, 6.19942589e-05, 3.93874172e-04,
       7.48660761e-05, 1.12449991e-04, 5.53204240e-04, 3.39292072e-04]), 'mean_score_time': array([0.0036541 , 0.00204105, 0.00203576, 0.00202947, 0.00218954,
       0.00195427, 0.00200095, 0.00266209]), 'std_score_time': array([3.04558003e-03, 1.40665458e-04, 4.07762968e-05, 5.32621770e-05,
       5.71396575e-05, 9.47429236e-05, 1.17200482e-04, 1.23534653e-03]), 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
             mask=[False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                   'rbf', 'linear'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 1, 'kernel': 'rbf'}, {'C': 1, 'kernel': 'linear'}, {'C': 10, 'kernel': 'rbf'}, {'C': 10, 'kernel': 'linear'}, {'C': 20, 'kernel': 'rbf'}, {'C': 20, 'kernel': 'linear'}, {'C': 30, 'kernel': 'rbf'}, {'C': 30, 'kernel': 'linear'}], 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
       1.        , 0.96666667, 1.        ]), 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]), 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
       0.9       , 0.9       , 0.9       ]), 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.93333333, 0.93333333, 0.9       ]), 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]), 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
       0.96666667, 0.96      , 0.96      ]), 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
       0.0421637 , 0.03887301, 0.04898979]), 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [212]:
results = pd.DataFrame(classifier.cv_results_)

In [213]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004824,0.003892,0.003654,0.003046,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002627,0.000288,0.002041,0.000141,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002702,0.000062,0.002036,0.000041,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002960,0.000394,0.002029,0.000053,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002748,0.000075,0.002190,0.000057,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002537,0.000112,0.001954,0.000095,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002942,0.000553,0.002001,0.000117,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002863,0.000339,0.002662,0.001235,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [214]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

# Random Search CV

In [215]:
from sklearn.model_selection import RandomizedSearchCV

In [219]:
classifier_random = RandomizedSearchCV((model_svm),{
    "C":[1,10,20,30],
    'kernel':['rbf','linear']
},n_iter = 4,cv=5,return_train_score=False)

In [220]:
classifier_random.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [222]:
results = pd.DataFrame(classifier_random.cv_results_)

In [223]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005942,0.003829,0.004266,0.002403,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
1,0.003094,0.000091,0.002252,0.000106,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002874,0.000076,0.002138,0.000040,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003743,0.001378,0.002111,0.000337,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4

In [225]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20          rbf         0.966667
1        1          rbf         0.980000
2        1       linear         0.980000
3       30          rbf         0.960000